<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_t Li Mt Khu_verifyPassword</name>
   <tag></tag>
   <elementGuidId>f7cace45-54d9-47e0-8b8d-ca86657f1eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-9.mt-3.password_container > #inputPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='inputPassword'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0177a960-ba1f-47cc-bee6-0263964ca6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>194f6bd0-f013-429b-b7bf-ee46bb33eea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPassword</value>
      <webElementGuid>863a974f-ed6b-4e3d-8f60-0a551f5db9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md </value>
      <webElementGuid>e526c66f-681c-4b49-a460-010bf2c8f103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verifyPassword</value>
      <webElementGuid>cc1c5429-000f-4cc5-b510-6f7311d7e57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xác Nhận Lại Mật Khẩu</value>
      <webElementGuid>b56dfd48-2c9c-4bad-819c-c010538cb4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;m-article&quot;]/div[1]/div[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;p-5 shadow box-resetPassword&quot;]/div[2]/div[@class=&quot;form-group row d-flex justify-content-center mt-4&quot;]/div[@class=&quot;col-sm-9 mt-3 password_container&quot;]/input[@id=&quot;inputPassword&quot;]</value>
      <webElementGuid>62aff2a7-99a9-4aac-ad7e-becaa542e3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='inputPassword'])[2]</value>
      <webElementGuid>9ef66e41-76a8-45d8-a0b8-09620b2042b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>5cac776e-16a7-47d8-a09b-ed682f083bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e8a58658-7dd8-491f-bb71-8a0f35009b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'inputPassword' and @name = 'verifyPassword' and @placeholder = 'Xác Nhận Lại Mật Khẩu']</value>
      <webElementGuid>5b0ba72c-cd85-4cbc-8d24-d12216dded8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
