<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhp M OTP_otp</name>
   <tag></tag>
   <elementGuidId>c04e2bce-cab5-452c-8a03-336e17161543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otp&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd27ed1e-d132-44a9-9d5e-43ee61533e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>cefbdd26-8063-4342-986d-148e4c4e4efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c92b97e8-41e6-4f8f-8fef-6b8669029b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md</value>
      <webElementGuid>0fb4feb2-e9ed-4e6c-b632-ccdfb42fc8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>b07ef06a-f177-4686-a15a-7b430ab2b476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>OTP</value>
      <webElementGuid>63be1bee-077c-4510-9849-ed4ea7175d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;m-article&quot;]/div[1]/div[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;p-5 shadow box-resetPassword&quot;]/div[2]/div[@class=&quot;form-group row d-flex justify-content-center mt-4&quot;]/div[@class=&quot;col-sm-9&quot;]/input[@class=&quot;form-control form-control-md&quot;]</value>
      <webElementGuid>c5d17127-ef9a-4e79-8258-9dec3ab3baf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otp']</value>
      <webElementGuid>399f6bd8-1de2-4a7c-b0c2-06aef263fee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>102d80dd-c6e1-4a9b-9dbb-d4f3ca130f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>522a148c-dadb-4a02-8fa8-59aa398242f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'otp' and @placeholder = 'OTP']</value>
      <webElementGuid>db8492bc-fe52-4af4-9852-3f0494c4c086</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
