<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N_address</name>
   <tag></tag>
   <elementGuidId>0bc177ed-1aef-43a9-b0cd-cb70ea5655e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='formGroupExampleInput2'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f215d02f-8c03-4d2b-b269-192c688d4a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c1d2b8c-46f6-431f-945a-f6e1a5f9adcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6df50b66-c88a-45ed-84c7-ab3d049a4dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGroupExampleInput2</value>
      <webElementGuid>c2fec4d1-9e62-415e-bde9-01c335f1b657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>68fd5d8d-f7f0-4e66-921b-5038dbe2499c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa Chỉ</value>
      <webElementGuid>f2af5fb2-0457-4134-9788-56caba2ab397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>828 sư vạn hạnh</value>
      <webElementGuid>2abc3730-9550-4e0e-89f6-0821c9f6ec6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;m-article&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row mt-5 justify-content-center&quot;]/div[@class=&quot;col-9 ml-2 shadow&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;row&quot;]/form[1]/div[@class=&quot;form-group mt-3&quot;]/input[@id=&quot;formGroupExampleInput2&quot;]</value>
      <webElementGuid>883d76e7-0e79-47e1-98c1-119fc121938a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='formGroupExampleInput2'])[2]</value>
      <webElementGuid>0dc25dc3-7921-4929-918e-0cd175e7c92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div[3]/form/div[4]/input</value>
      <webElementGuid>fad547c2-77ea-41c9-8c85-e2a8a269fa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>f075b993-8570-4011-8569-a33a4193eaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formGroupExampleInput2' and @name = 'address' and @placeholder = 'Địa Chỉ']</value>
      <webElementGuid>a7a36950-bb64-432e-8ebc-8ef1da07ec3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
