<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N_dateOfBirth</name>
   <tag></tag>
   <elementGuidId>430e0f64-61f8-466f-91b4-20079e55c2e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGroupExampleInput2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formGroupExampleInput2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1778e10e-b1c6-4992-b383-f78a9cc5ba24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d09ad4d-3f88-4804-b007-a1dcb498579e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>862caf64-d470-4c50-a247-3c8a3dcdeac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGroupExampleInput2</value>
      <webElementGuid>4fb20dcd-0bd5-4e6c-9ee9-3e70d9cd4b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ngày Sinh</value>
      <webElementGuid>b19aa394-9e1b-49ef-a54b-f73f1e2b0a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dateOfBirth</value>
      <webElementGuid>2d7e1b46-296e-4600-8e42-3c784d997bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12/01/2001</value>
      <webElementGuid>e9247eb4-3b45-46ff-93ff-0aa82ffb16c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;m-article&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row mt-5 justify-content-center&quot;]/div[@class=&quot;col-9 ml-2 shadow&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;row&quot;]/form[1]/div[@class=&quot;form-group mt-3&quot;]/input[@id=&quot;formGroupExampleInput2&quot;]</value>
      <webElementGuid>d60b004d-19b2-41a7-803e-6efca9cbfe99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGroupExampleInput2']</value>
      <webElementGuid>ecca3875-4903-4d21-a560-c9364fa60717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div[3]/form/div[3]/input</value>
      <webElementGuid>47a68235-0798-47cf-a061-32e2e8bdecbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e4ecb0dd-874b-4c79-9fce-f63d2e553fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formGroupExampleInput2' and @placeholder = 'Ngày Sinh' and @name = 'dateOfBirth']</value>
      <webElementGuid>8d55fffd-0f07-434e-bdc6-9342ae75dde4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
