<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstHotItem</name>
   <tag></tag>
   <elementGuidId>ac1e36a5-d650-48c8-9977-409330462db9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.stretched-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div/div[3]/div/div/div/div/div[1]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a00f368-07d7-46e4-af9c-bfffb760c905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stretched-link</value>
      <webElementGuid>44ff9e8a-36da-4e81-921f-0570143567e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product/6232fbf301830a245b8d7516</value>
      <webElementGuid>0cd3244c-d716-4efb-9480-7f41789e9e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;m-article&quot;]/div[1]/div[3]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card-group&quot;]/div[@class=&quot;row row-cols-1 row-cols-md-3 row-cols-lg-3&quot;]/div[@class=&quot;col border border-0  card&quot;]/div[@class=&quot;card-body&quot;]/a[@class=&quot;stretched-link&quot;]</value>
      <webElementGuid>83af72f4-7ecf-4605-b438-ef410e7d09e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/div/div/div/div/a</value>
      <webElementGuid>e69c100d-3ce7-42e5-a864-93702b55cf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/product/6232fbf301830a245b8d7516')]</value>
      <webElementGuid>02f100e3-ec86-42b6-abd9-10144cf80cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>0a037651-da04-4d45-9570-b46d83f5e885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/product/6232fbf301830a245b8d7516']</value>
      <webElementGuid>506d8665-1881-44ea-9b41-54db52a4821f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
