<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popOverLogin</name>
   <tag></tag>
   <elementGuidId>9f299dfe-6207-427a-83eb-603e1eac3ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/nav/div/div[2]/ul[2]/li[3]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f9af1651-3be3-48c6-97be-77045f924ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-user</value>
      <webElementGuid>0caa1f4e-a299-4ed8-8ddf-c4c44c35d86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;header-custom&quot;]/div[@class=&quot;m-nav&quot;]/div[@class=&quot;container-fluid&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;collapse navbar-collapse&quot;]/ul[@class=&quot;d-none d-lg-flex align-items-center navbar-nav&quot;]/li[@class=&quot;nav-item&quot;]/span[@class=&quot;MuiBadge-root MuiBadge-root css-1rzb3uu&quot;]/i[@class=&quot;bx bx-user&quot;]</value>
      <webElementGuid>bd842fb9-6c1a-4b61-83b1-af69645da913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/nav/div/div[2]/ul[2]/li[3]/span/i</value>
      <webElementGuid>6ba71024-859d-438a-bed2-e537027ed9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/i</value>
      <webElementGuid>f2101eed-af10-4a52-8e38-d28b59572cd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
