<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng nhp_nameCustomer</name>
   <tag></tag>
   <elementGuidId>86b45aad-7c1a-44d0-b148-037c83db1803</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nameCustomer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nameCustomer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65132e67-4517-4b86-88a0-15e590e3b622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>611a9877-8206-4755-aefa-159cafa6c287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameCustomer</value>
      <webElementGuid>c811a78c-8830-4715-9b27-2be6bec91916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9e54c13c-6d8a-4f05-896e-10dd6d7309b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Họ và tên</value>
      <webElementGuid>761434ed-cb50-4019-a4cb-8fb463010bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;m-article&quot;]/div[@class=&quot;container pe-5 my-5&quot;]/div[@class=&quot;row row-cols-1 row-cols-md-1 row-cols-lg-2&quot;]/div[@class=&quot;col col-left pe-5 pt-5&quot;]/form[@class=&quot;section&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>4745e75b-5366-4d6e-85cc-c64fffa493b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nameCustomer']</value>
      <webElementGuid>a598f337-6b3c-46a4-adbc-6da263d95743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/form/input</value>
      <webElementGuid>5db0661c-a9fe-47a2-bc60-a4e542267c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>e236d0b0-cd5e-4f6f-9bd1-0569ab5c22eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nameCustomer' and @placeholder = 'Họ và tên']</value>
      <webElementGuid>a5e9b372-18ab-4c96-b2d0-7faebdc0a058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
