<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng nhp_phoneNumber</name>
   <tag></tag>
   <elementGuidId>30e24188-7bcc-435a-99de-00dbe5768c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phoneNumber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6e822e2-47b4-4953-bc68-20a6613049b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3f06167-0543-4f81-9b95-aba2e1314cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>dc0fcdd1-8fcc-4c26-a4ab-248a9ea81624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6e452a3d-acc6-4780-aacf-b7edd0a14563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Số điện thoại</value>
      <webElementGuid>88eec1fb-19cd-48f5-a9ab-d70470803442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;m-article&quot;]/div[@class=&quot;container pe-5 my-5&quot;]/div[@class=&quot;row row-cols-1 row-cols-md-1 row-cols-lg-2&quot;]/div[@class=&quot;col col-left pe-5 pt-5&quot;]/form[@class=&quot;section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-4&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>87664699-7104-4fe0-b050-3d5e9d7d4bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phoneNumber']</value>
      <webElementGuid>3707e12d-1b64-4d40-9be6-7cd347cf33ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>a45cae7b-f385-4d62-b7b1-773d02fa241a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>244ee358-2d19-4712-b4de-2ba416696bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'phoneNumber' and @placeholder = 'Số điện thoại']</value>
      <webElementGuid>582dd0d0-7a63-4b2f-b133-65a125c863a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
