<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhp email v mt khu ca bn_exampleDropd_684f84</name>
   <tag></tag>
   <elementGuidId>89e8edb1-6acc-4bea-9533-6328d6090d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exampleDropdownFormPassword1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exampleDropdownFormPassword1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a2a60b8-a7ee-4c2c-baef-b7a8137a43d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>265f8a19-6c37-4464-a443-70387538cec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5c152cd8-8f9b-4779-bf37-431830d548f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleDropdownFormPassword1</value>
      <webElementGuid>1f65cdf8-4ed5-4669-a008-7cec20be391b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>0a060b2c-c85a-4880-9a4f-8f9c4051d700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleDropdownFormPassword1&quot;)</value>
      <webElementGuid>519a7633-0d2c-4b78-8c70-cfa4549ab019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exampleDropdownFormPassword1']</value>
      <webElementGuid>b4340cd8-a95b-4ecf-b0a6-8fb99d2848cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-container']/form/div[2]/input</value>
      <webElementGuid>9960ae54-0751-4ad7-9716-acbca46f7528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7a5e098c-d8a6-46c5-97d7-a4e35141814e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'exampleDropdownFormPassword1' and @placeholder = 'Password']</value>
      <webElementGuid>f93d679e-c5dc-4432-9a38-c6b5576be52b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
