<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhp email v mt khu ca bn_exampleDropd_db6b01</name>
   <tag></tag>
   <elementGuidId>7de0653b-df4d-4328-8ce9-47ca4f37e91a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exampleDropdownFormEmail1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exampleDropdownFormEmail1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>500d6704-cae5-426c-ab03-da18619d5151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>cf496330-d46b-4397-9d8b-8284ebb0e17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4f291436-35d7-4b33-a6ba-1f821b4f9133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleDropdownFormEmail1</value>
      <webElementGuid>9048d01d-208a-4ef3-99ac-8066fc006e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>88878549-c937-4153-8f3b-3d7146e26bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleDropdownFormEmail1&quot;)</value>
      <webElementGuid>bcca164d-5b43-4e11-93c5-0e6c4f20958f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exampleDropdownFormEmail1']</value>
      <webElementGuid>3075efa8-f067-4cae-9162-5b6ced42b482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-container']/form/div/input</value>
      <webElementGuid>1834cc3d-ec05-43e7-90b6-000ee0a8b678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>89a10464-ed2e-4125-bc5f-352821e2541a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'exampleDropdownFormEmail1' and @placeholder = 'Email']</value>
      <webElementGuid>3d439639-c7c1-49dc-bcf0-d737d5d0e50d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
