<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sn phm mi NEW ARRIVALS</name>
   <tag></tag>
   <elementGuidId>a4a9164d-776c-40d1-973c-71c57cfadd2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sub-nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[1]/div/div/nav/div/div[2]/ul[1]/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6cf2347a-486e-4075-a93a-53c419401add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-nav-link</value>
      <webElementGuid>5b8e8a74-0e4d-4149-9eee-504ee7d8d2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categories/new-arrivals</value>
      <webElementGuid>fb4aa266-f5c4-47c9-8f64-f43a216ec2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sản phẩm mới︱ NEW ARRIVALS</value>
      <webElementGuid>fce9b813-8e39-43a3-9cfd-6977438e97e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;m-main&quot;]/div[@class=&quot;header-custom&quot;]/div[@class=&quot;m-nav&quot;]/div[@class=&quot;container-fluid&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;collapse navbar-collapse&quot;]/ul[@class=&quot;me-auto align-items-lg-center navbar-nav&quot;]/li[@class=&quot;sub-nav nav-item&quot;]/div[@class=&quot;sub-nav-content&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;sub-nav-link&quot;]</value>
      <webElementGuid>bda21cb9-a41c-4aff-b1aa-957733665911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/nav/div/div[2]/ul/li[3]/div/li/a</value>
      <webElementGuid>88806af4-fa22-4dd0-9478-39dc0060ef6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sản phẩm mới︱ NEW ARRIVALS')]</value>
      <webElementGuid>c7fc7817-e240-45bb-a9cb-38c393073796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục sản phẩm'])[1]/following::a[1]</value>
      <webElementGuid>74a1ff50-2d57-421b-ae72-c6fdc08ee4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/following::a[2]</value>
      <webElementGuid>7763b383-1e4c-4d35-8b8f-fc8c45586cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áo︱TOPS'])[1]/preceding::a[1]</value>
      <webElementGuid>cf34caa4-e3ef-4bd8-9428-544eb605cd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần︱ BOTTOMS'])[1]/preceding::a[2]</value>
      <webElementGuid>4ffff784-4315-4411-91d5-0d97e9779c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sản phẩm mới︱ NEW ARRIVALS']/parent::*</value>
      <webElementGuid>05175e2f-0807-4502-acbb-092de8676259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/categories/new-arrivals')])[2]</value>
      <webElementGuid>08621be9-3930-4762-9f84-41ea92b1077e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li/a</value>
      <webElementGuid>6c4e4a01-e817-4729-af23-e32e52a30d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/categories/new-arrivals' and (text() = 'Sản phẩm mới︱ NEW ARRIVALS' or . = 'Sản phẩm mới︱ NEW ARRIVALS')]</value>
      <webElementGuid>98bd11f1-5e1b-4ac3-8bc9-b695d559ef09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
