<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product</name>
   <tag></tag>
   <elementGuidId>0d5140aa-0350-4d5b-b7cc-15755bded4b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.stretched-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div/div[2]/div[3]/div/div/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8ffed3c8-d1af-4120-89fe-5788556017f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stretched-link</value>
      <webElementGuid>bedf186d-71b6-4c29-977f-66bb604d7dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product/6232fbf301830a245b8d7528</value>
      <webElementGuid>e5c5d623-aef0-44b5-8012-969b1515207a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collections&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card-group&quot;]/div[@class=&quot;row row-cols-1 row-cols-md-3 row-cols-lg-3&quot;]/div[@class=&quot;col border border-0  card&quot;]/div[@class=&quot;card-body&quot;]/a[@class=&quot;stretched-link&quot;]</value>
      <webElementGuid>599b63e9-b5f4-4939-97ca-b3eaa1967f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collections']/div/div/div/div/div/div/a</value>
      <webElementGuid>9a789c2d-f3f2-4947-8e91-cf69f44494f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/product/6232fbf301830a245b8d7528')]</value>
      <webElementGuid>58484c3a-707c-4294-9a00-283acdd0ac54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>d402d2eb-9e5b-40dc-8b31-d62a584e8fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/product/6232fbf301830a245b8d7528']</value>
      <webElementGuid>026c72e0-2085-401b-89a3-ed6a06710358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
