<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Voucher</name>
   <tag></tag>
   <elementGuidId>8cdd275f-8c3b-45b4-94ea-5c9836af9622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/ul/a[4]/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e91dbbf1-3a1b-4aca-a923-813ca26c970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebarListItem</value>
      <webElementGuid>e63847de-b4ac-4bb9-b47f-7acd9644437a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Voucher</value>
      <webElementGuid>ea31899f-6764-4e40-9c67-d8a1d41a87c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;respon&quot;]/div[@class=&quot;sidebar&quot;]/div[@class=&quot;sidebarWrapper&quot;]/div[@class=&quot;sidebarMenu&quot;]/ul[@class=&quot;sidebarList&quot;]/a[@class=&quot;link&quot;]/li[@class=&quot;sidebarListItem&quot;]</value>
      <webElementGuid>0ceb7bee-1427-4e08-a495-f24bd897dbd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/ul/a[4]/li</value>
      <webElementGuid>c299987d-1e72-43a7-9c2f-f99dea962134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hóa Đơn'])[1]/following::li[1]</value>
      <webElementGuid>5f9a6ba7-6be0-4af8-a26a-57a7720852eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản Phẩm'])[1]/following::li[2]</value>
      <webElementGuid>ea1528ce-53d9-4e0e-84d2-edda8df3c380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::li[1]</value>
      <webElementGuid>8c68a7be-b535-4660-aa1b-389b293209fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::li[1]</value>
      <webElementGuid>a4c74993-80ec-4101-b5ec-15feca6472a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Voucher']/parent::*</value>
      <webElementGuid>b8b05726-9c5d-4c36-a683-f3a4c9bf9158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/li</value>
      <webElementGuid>c98b2e9a-c23e-4a16-8177-d43bf2b821c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Voucher' or . = 'Voucher')]</value>
      <webElementGuid>ed86c9e2-b3ad-427e-8083-03f6808a70fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
