<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>voucherLink</name>
   <tag></tag>
   <elementGuidId>8cdd275f-8c3b-45b4-94ea-5c9836af9622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[1]/div/div[2]/ul/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5570eb91-2ce3-4df6-b47f-6d0f4f605718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebarListItem</value>
      <webElementGuid>0f3c080f-fd28-4e84-b315-df829a22a75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Voucher</value>
      <webElementGuid>110c9d27-afe1-480a-b73e-87de5ee180b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;respon&quot;]/div[@class=&quot;sidebar&quot;]/div[@class=&quot;sidebarWrapper&quot;]/div[@class=&quot;sidebarMenu&quot;]/ul[@class=&quot;sidebarList&quot;]/a[@class=&quot;link&quot;]/li[@class=&quot;sidebarListItem&quot;]</value>
      <webElementGuid>a32941ff-6920-41d7-a1ad-6e3b343ff603</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/ul/a[4]/li</value>
      <webElementGuid>c776dcc4-77e3-4a14-a4fd-7a8f3c332049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hóa Đơn'])[1]/following::li[1]</value>
      <webElementGuid>4c6692e9-c61a-4e7c-afcf-3617bb6b3f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản Phẩm'])[1]/following::li[2]</value>
      <webElementGuid>b70ab3da-d455-41c4-9876-f1842c56b3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::li[1]</value>
      <webElementGuid>04d63e96-5ac3-47e6-9bbb-ee6488a199bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::li[1]</value>
      <webElementGuid>be1c9973-19d3-41d6-af75-7ea32df97e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Voucher']/parent::*</value>
      <webElementGuid>b1d242af-6116-431c-86a9-80e40bf5d94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/li</value>
      <webElementGuid>7e6e02f3-50a5-4e70-a1d7-6a952c4c5b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Voucher' or . = 'Voucher')]</value>
      <webElementGuid>fa6ab033-24f0-4777-9ab2-3d2e4f80a2f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
