<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To ti khon_address</name>
   <tag></tag>
   <elementGuidId>09db1a14-1c77-4303-8a19-0b55e66d28db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88ad9897-ff2c-4827-867b-66109a6b6474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e681214-69c1-4855-aac0-377789b9e15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>906bbba5-c72f-4ee9-9432-22f6d7ba59c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa Chỉ</value>
      <webElementGuid>19663194-dc2c-422a-bb6e-80d0bf1e8b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>87bbf392-ca33-4a8a-abb2-709e89aa7d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f76bb3e-6676-4e0d-9d1e-e31741b053e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>49c1f7ad-301b-449a-a2ff-24aac44a5602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first_name&quot;)</value>
      <webElementGuid>6a28a417-1229-4e1d-b3c6-e8435f91afc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>89cdc825-73b8-4885-b158-5776b8f977b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='first_name']</value>
      <webElementGuid>624bcdab-cdaf-4264-bd25-59c49974d66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-first_name']/input</value>
      <webElementGuid>e0b5e312-5009-43a5-a255-97677a6a10a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>464d51d4-d8b3-40a8-b20b-074d77815e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address' and @placeholder = 'Địa Chỉ' and @id = 'first_name']</value>
      <webElementGuid>d61ffdf1-eee9-4420-b5ea-8848b6a96af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
